service: audio-merge

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::matedub-api-export-staging/*"
        - "arn:aws:s3:::matesub-video-optimized/*"
        - "arn:aws:s3:::matedub-api-cache-files-staging/*"

functions:
  mergeAudio:
    handler: handler.lambda_handler
    timeout: 600
    layers:
      - arn:aws:lambda:eu-central-1:208060995276:layer:ffmpeg:1  # Prebuilt FFmpeg layer
    events:
      - http:
          path: merge
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true  # Use Docker to install Python packages

package:
  exclude:
    - node_modules/**
    - venv/**
